services:
  db:
    container_name: moc_2025_postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  app:
    container_name: moc_2025_be
    platform: linux/x86_64
    stdin_open: true
    tty: true
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    command: sh /docker-entrypoint.sh
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    # environment:
    #   RAILS_ENV: ${RAILS_ENV}
    #   DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #   DATABASE_HOST: ${DATABASE_HOST}
    #   DATABASE_PORT: ${DATABASE_PORT}
    #   DATABASE_USER: ${DATABASE_USER}
    #   DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db
    volumes:
      - .:/workspace
      - bundle:/workspace/vendor/bundle

volumes:
  bundle:
