FROM ruby:3.2.2-alpine

ENV LANG C.UTF-8

ARG APP_ROOT=/workspace
ARG BUILD_PACKAGES="vim curl curl-dev ruby-dev build-base bash less"
ARG DEV_PACKAGES="zlib-dev libxml2-dev libxslt-dev tzdata yaml-dev libpq-dev git nodejs npm"
ARG RUBY_PACKAGES="tzdata ruby-json yaml"

RUN apk add --update \
  $BUILD_PACKAGES \
  $DEV_PACKAGES \
  $RUBY_PACKAGES

RUN mkdir -p $APP_ROOT
WORKDIR $APP_ROOT

ENV GEM_HOME /$APP_ROOT/vendor/bundle
ENV BUNDLE_PATH /$APP_ROOT/vendor/bundle
ENV BUNDLE_BIN /$APP_ROOT/vendor/bundle/bin
ENV PATH $BUNDLE_BIN:$BUNDLE_PATH/gems/bin:$PATH

RUN rails assets:precompile
COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

EXPOSE ${APP_PORT}
