default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  checkout_timeout: 10
development:
  <<: *default
  database: zigexn_vn_2025_be_development

test:
  <<: *default
  database: zigexn_vn_2025_be_test

production:
  <<: *default
  database: zigexn_vn_2025_be_production
