toolbar:
  - undo redo | formatselect | bold italic underline strikethrough | alignleft aligncenter alignright | bullist numlist outdent indent | link image | removeformat
plugins:
  - advlist
  - autolink
  - lists
  - link
  - image
  - charmap
  - preview
  - anchor
  - searchreplace
  - visualblocks
  - code
  - fullscreen
  - insertdatetime
  - media
  - table
height: 300
menubar: false 